@startuml systemEntities

entity Пользователь {
    Email
    Пароль
    Роль
}

entity Аккаунт {
    ID
    ФИО
    День рождения
    Пол
    Email
}

entity Соревнование {
    ID
    Дата
    Возрастая категория
    Тип оружия
    Вид
    Пол
    Командные
    Число спортсменов
}

entity Бой {
    ID
    ID победителя
    ID проигравшего
    ID соревнования
    Счет победителя
    Счет проишравшего
}

entity Спортсмен {
    ID
    ID аккаунта
    Тип оружия
    Вооруженная рука
    Лицензия
    Страховка
    Разряд
}

@enduml