@startuml er

left to right direction

entity Администратор {}
entity Спортсмен {
    ID
    Вооруженная рука
    Страховка
    Лицензия
    Оружие
    Разряд
}

entity Пользователь {
    ID 
    ФИО
    email
    Дата рождения
    Пол
}

entity Соревнование {
    ID
    Дата
    Возрастая категория
    Тип оружия
    Вид
    Тип
}

entity Бой {
    ID 
    ID соревнования
    ID победителя
    ID проигравшего
    Счет победителя
    Счет проишравшего
}

Соревнование ||-- Бой

Соревнование }o--o{ Пользователь : участвует, создает
Спортсмен -- Пользователь: имеет
Администратор -- Пользователь: имеет

@enduml