

@startuml usecase

left to right direction

:Гость: --> (Авторизация)
:Гость: --> (Просмотр общей информации \n о соревнованиях)

:Спортсмен: --> (Просмотр профиля)
:Спортсмен: --> (Просмотр общей информации \n о соревнованиях)
:Спортсмен: --> (Подача заявки на турнир)
:Спортсмен: --> (Отмена заявки на турнир)

' (Просмотр календаря \n соревнований) --> (Фильтрация данных)

:Администратор: --> (Редактирование информации \n о соревнованиях)
:Администратор: --> (Добавление соревнования)
:Администратор: --> (Удаление соревнования)
:Администратор: --> (Просмотр общей информации \n о соревнованиях)

@enduml
