port: 8080

auth:
  signing_key: "your_signing_key"
  hash_salt: "your_hash_salt"
  token_ttl: 86400

postgres:
  url: "host=localhost port=5432 dbname=fencing sslmode=disable user=postgres password=postgres"